name: protein-pocket
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - fpocket=4.2.2
  - openjdk=24.0.2
  - numpy
  - biopython
  - openbabel
  - pip
  - pip:
    - typer[all]
    - rich
    - pydantic
    - requests
